#!/bin/bash

# Capturando o texto a ser traduzido
printf "\033[1;36mInserir texto: \033[0m" && read TEXT
printf "\033[1;36mTraduzir para: \033[0m" && read LANG

# Definindo linguagem padrão e API key 
[ -z "$LANG" ] && LANG="en"
API="AIzaSyBE38k0D-2-RYSt72waX-Ld5sXfZ7k3cJM"

# Encodando texto para HTML
ENCODE=$(sed 's/ /%20/g' <<< "$TEXT")

# Fazendo uma requisição para o Google Tradutor e extraindo output
RESPONSE=$(curl -skL "https://translation.googleapis.com/language/translate/v2?key=$API&q=$ENCODE&target=$LANG" | jq -r '.data.translations[0].translatedText')

# Texto traduzido
printf "\033[1;36mTexto traduzido:\033[0m $RESPONSE\n"
